version: '3'
services:
  frontend:
    ports:
      - 8000:8000
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: frontend

  backend:
    build:
      dockerfile: Dockerfile
      context: backend
